development:
  access_key_id: 'AKIAJQW3JLR5363Y6OSA'
  secret_access_key: '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'
  bucket: 'glis-org-nano'

production:
  access_key_id: 'AKIAJQW3JLR5363Y6OSA'
  secret_access_key: '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'
  bucket: 'glis-org'